apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
  namespace: system
  annotations:
    iam.gke.io/gcp-service-account: namespace-controller@REDACTED.iam.gserviceaccount.com #TODO(rsong): seed with opensource context
