---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: developer
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - persistentvolumeclaims
      - serviceaccounts
      - secrets
      - configmaps
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - autoscaling.k8s.io
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - machinelearning.seldon.io
    resources:
      - seldondeployments
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - security.istio.io
    resources:
      - authorizationpolicies
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.istio.io
    resources:
      - destinationrules
      - serviceentries
      - sidecars
      - virtualservices
    verbs:
      - create
      - update
      - patch
      - delete
