# permissions for end users to view namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lnamespace-create-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-authenticated: "true"
rules:
  - apiGroups:
      - gial.lblw.dev
    resources:
      - lnamespaces
    verbs:
      - create
