# permissions for end users to view namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lnamespace-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - gial.lblw.dev
    resources:
      - lnamespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gial.lblw.dev
    resources:
      - lnamespaces/status
    verbs:
      - get
